version: '3.1'

services:
  db:
    image: postgres
    container_name: geodata
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Wc9T6pwQ7
      POSTGRES_DB: geodata
    volumes:
      - postgres_data:/var/lib/postgresql/data/

volumes:
  postgres_data:
