basePath: /
definitions:
  models.City:
    properties:
      area_ru:
        type: string
      country_id:
        type: integer
      id:
        type: integer
      region_ru:
        type: string
      title_ru:
        type: string
    type: object
  models.Country:
    properties:
      id:
        type: integer
      title_ru:
        type: string
    type: object
host: 188.225.72.165
info:
  contact: {}
  description: This is a api server for geo clue.
  title: Swagger Geo API
  version: "1.0"
paths:
  /city:
    get:
      parameters:
      - description: search city by str
        in: query
        name: str
        required: true
        type: string
      - description: search city by country
        in: query
        name: country
        type: integer
      - description: query limit
        in: query
        name: lim
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.City'
            type: array
      summary: Show a city list
  /country:
    get:
      parameters:
      - description: search country by str
        in: query
        name: str
        required: true
        type: string
      - description: query limit
        in: query
        name: lim
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.Country'
            type: array
      summary: Show a country list
schemes:
- http
swagger: "2.0"
